(define (sqrt-itr guess x)
	(if (good-enough? guess (improve guess x))
		guess
		(sqrt-itr (improve guess x)
				x)))
(define (improve guess x)
	(average guess (/ x guess)))
(define (average x y)
	(/ (+ x y) 2))
(define (good-enough? guess next-guess)
	(< (abs (- guess next-guess)) 0.001))
(define (square x)
	(* x x))
(define (my-sqrt x)
	(sqrt-itr 1.0 x))
